"""initial contents table

Revision ID: 9dadcfe381e2
Revises: 
Create Date: 2026-08-15 09:55:16.005328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dadcfe381e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('creator', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_logged_date'), ['logged_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_logged_date'))

    op.drop_table('contents')
    # ### end Alembic commands ###
